// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB28tyZAnWzmNvMKT_25-_OrUdz5x-fRkc',
    appId: '1:317378056004:web:a11f606986f286f8da9111',
    messagingSenderId: '317378056004',
    projectId: 'finbud-a0eb3',
    authDomain: 'finbud-a0eb3.firebaseapp.com',
    storageBucket: 'finbud-a0eb3.appspot.com',
    measurementId: 'G-92BDGHGG1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYe0GLolPzi5bx1gfXc-s9VaYfHInMv-E',
    appId: '1:317378056004:android:ae9fd7e206e7b679da9111',
    messagingSenderId: '317378056004',
    projectId: 'finbud-a0eb3',
    storageBucket: 'finbud-a0eb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5RbagYBxiDxb9h-GnJvaB7o3ZKSXCQjw',
    appId: '1:317378056004:ios:8a99e6e83176fb5bda9111',
    messagingSenderId: '317378056004',
    projectId: 'finbud-a0eb3',
    storageBucket: 'finbud-a0eb3.appspot.com',
    iosBundleId: 'com.example.finbudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5RbagYBxiDxb9h-GnJvaB7o3ZKSXCQjw',
    appId: '1:317378056004:ios:fcf84313ee47b77bda9111',
    messagingSenderId: '317378056004',
    projectId: 'finbud-a0eb3',
    storageBucket: 'finbud-a0eb3.appspot.com',
    iosBundleId: 'com.example.finbudApp.RunnerTests',
  );
}
